resources:
  repositories:
    - repository: pipeline-templates
      type: git
      name: Oil/pipeline-templates
      ref: refs/heads/main

extends:
  template: templates/python-packages-pipeline.yml@pipeline-templates
  parameters:
    packageName: 'futureskit'
    createRefinitivConfig: false

pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
      - main
  tags:
    include:
      - "*"

variables:
  pythonVersion: '3.10'

jobs:
- job: BuildAndPublish
  displayName: 'Build and Publish Package'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
    displayName: 'Use Python $(pythonVersion)'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install build wheel
    displayName: 'Install build tools'

  - script: |
      python -m build
    displayName: 'Build package'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'dist'
      artifact: 'futureskit-package'
      publishLocation: 'pipeline'
    displayName: 'Publish package artifacts'

  - script: |
      ls -la dist/
    displayName: 'List built artifacts'