resources:
  repositories:
    - repository: pipeline-templates
      type: git
      name: Oil/pipeline-templates
      ref: refs/heads/main

extends:
  template: templates/python-packages-pipeline.yml@pipeline-templates
  parameters:
    packageName: 'futureskit'
    createRefinitivConfig: false


trigger:
  branches:
    include:
      - main
  tags:
    include:
      - "*"